-- Run after scripts/01_reset_all_data.sql
-- psql -U postgres -f scripts/02_seed_admin_accounts.sql

\connect swp_auth_db;
BEGIN;

ALTER TABLE public."Users" ADD COLUMN IF NOT EXISTS "FullName" character varying(150);
ALTER TABLE public."Users" ADD COLUMN IF NOT EXISTS "RequestedRole" text;

UPDATE public."Users"
SET "FullName" = COALESCE("FullName", split_part("Email", '@', 1));

ALTER TABLE public."Users" ALTER COLUMN "FullName" SET NOT NULL;

-- Password for both admin accounts: 123456
-- ASP.NET Identity hash generated by PasswordHasher (compatible with current login flow)
INSERT INTO public."Users" ("Id", "FullName", "Email", "PasswordHash", "Role", "RequestedRole")
VALUES
('10000000-0000-0000-0000-000000000001'::uuid, 'System Admin', 'admin@swp.local', 'AQAAAAIAAYagAAAAEF6YsDoIQat1p541CurzCqeSZliXJd+gt/k0uCjjHf2LCHzXnXbWdUGHmWKFIFsT3Q==', 'ADMIN', NULL),
('10000000-0000-0000-0000-000000000002'::uuid, 'Backup Admin', 'admin2@swp.local', 'AQAAAAIAAYagAAAAEF6YsDoIQat1p541CurzCqeSZliXJd+gt/k0uCjjHf2LCHzXnXbWdUGHmWKFIFsT3Q==', 'ADMIN', NULL)
ON CONFLICT ("Email")
DO UPDATE SET
    "FullName" = EXCLUDED."FullName",
    "PasswordHash" = EXCLUDED."PasswordHash",
    "Role" = 'ADMIN',
    "RequestedRole" = NULL;

COMMIT;

SELECT "Id", "FullName", "Email", "Role", "RequestedRole"
FROM public."Users"
ORDER BY "Email";
